// Generated by CoffeeScript 1.10.0
var EventEmitter, e;

EventEmitter = require('events').EventEmitter;

e = new EventEmitter;

e.on('event', function() {
  return console.log('event called');
});

e.emit('event');
